remote_theme: riggraz/no-style-please
title: ChrisArchitect
author: ChrisArchitect
url: https://chrisarchitect.dev # root address of the site
# baseurl: "/no-style-please" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: Some of my answers you will understand, and some of them you will not.

# permalink: /:slug.html

# favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics
goat_counter: G-S7PGM3WS0K

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  # back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
